// src/app/components/cart/cart.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { CartService, CartItem } from '../../services/cart.service';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-cart',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
    <div class="container-fluid px-0 bg-midnight-black min-vh-100 bg-gradient-purple">
      <div class="container py-5">
        <h2 class="mb-4 font-orbitron text-cyber-yellow">Shopping Cart</h2>
        <div *ngIf="items.length; else emptyCart">
          <div class="card glassy-card p-4 mb-4">
            <table class="table align-middle mb-4 text-white">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Price</th>
                  <th>Quantity</th>
                  <th>Subtotal</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let item of items">
                  <td class="py-3">
                    <img [src]="item.product.imageUrl" [alt]="item.product.title" width="40" class="me-2 rounded shadow-electric-purple img-thumbnail-glow">
                    <span class="fw-bold text-cyber-yellow">{{ item.product.title }}</span>
                  </td>
                  <td class="py-3 text-cyber-yellow">&euro;{{ item.product.price.toFixed(2) }}</td>
                  <td class="py-3">
                    <input type="number" min="1" class="form-control form-control-sm w-auto d-inline bg-midnight-black text-cyber-yellow border-electric-purple" [(ngModel)]="item.quantity" (change)="updateQuantity(item)">
                  </td>
                  <td class="py-3 text-cyber-yellow">&euro;{{ (item.product.price * item.quantity).toFixed(2) }}</td>
                  <td class="py-3">
                    <button class="btn btn-sm btn-danger" (click)="remove(item.product.id)"><i class="bi bi-trash"></i></button>
                  </td>
                </tr>
              </tbody>
            </table>
            <div class="d-flex flex-column flex-md-row justify-content-between align-items-center gap-3 mt-4">
              <a routerLink="/" class="btn btn-link mb-2 mb-md-0 text-cyber-yellow">Continue Shopping</a>
              <div>
                <span class="fw-bold me-3 fs-5 text-cyber-yellow">Total: &euro;{{ total.toFixed(2) }}</span>
                <button class="btn cta-future" [disabled]="!items.length">Checkout</button>
              </div>
            </div>
          </div>
        </div>
        <ng-template #emptyCart>
          <div class="alert alert-info mb-3 glassy-card p-4">Your cart is empty.</div>
          <a routerLink="/" class="btn cta-future">Shop Now</a>
        </ng-template>
      </div>
    </div>
  `
})
export class CartComponent {
  items: CartItem[] = [];
  total = 0;

  constructor(private cartService: CartService) {
    this.refresh();
  }

  refresh() {
    this.items = this.cartService.getItems();
    this.total = this.cartService.getTotal();
  }

  updateQuantity(item: CartItem) {
    this.cartService.updateQuantity(item.product.id, item.quantity);
    this.refresh();
  }

  remove(productId: string) {
    this.cartService.removeFromCart(productId);
    this.refresh();
  }
}

// src/app/cart/page.tsx
"use client";

import { useCart } from '@/lib/cart-context';
import Link from 'next/link';

export default function CartPage() {
  const { state, dispatch } = useCart();
  const cart = state.items;

  const handleRemove = (productId: string) => {
    dispatch({ type: 'REMOVE_ITEM', payload: { productId } });
  };

  const handleQuantityChange = (productId: string, quantity: number) => {
    if (quantity < 1) return;
    dispatch({ type: 'UPDATE_QUANTITY', payload: { productId, quantity } });
  };

  return (
    <div className="container py-5">
      <h1 className="display-4 mb-4">Your Cart</h1>
      {cart.length > 0 ? (
        <>
          <div className="row g-4 mb-4">
            {cart.map((item) => (
              <div key={item.product.id} className="col-12 col-md-6 col-lg-4">
                <div className="card h-100">
                  <img src={item.product.image} alt={item.product.name} className="card-img-top" />
                  <div className="card-body">
                    <h5 className="card-title">{item.product.name}</h5>
                    <p className="card-text">${item.product.price.toFixed(2)}</p>
                    <div className="d-flex align-items-center mb-2">
                      <button
                        className="btn btn-outline-secondary btn-sm me-2"
                        onClick={() => handleQuantityChange(item.product.id, item.quantity - 1)}
                        aria-label="Decrease quantity"
                        disabled={item.quantity <= 1}
                      >
                        <i className="bi bi-dash"></i>
                      </button>
                      <input
                        type="number"
                        className="form-control form-control-sm text-center"
                        style={{ width: 50 }}
                        value={item.quantity}
                        min={1}
                        onChange={e => handleQuantityChange(item.product.id, Number(e.target.value))}
                      />
                      <button
                        className="btn btn-outline-secondary btn-sm ms-2"
                        onClick={() => handleQuantityChange(item.product.id, item.quantity + 1)}
                        aria-label="Increase quantity"
                      >
                        <i className="bi bi-plus"></i>
                      </button>
                      <button
                        className="btn btn-outline-danger btn-sm ms-3"
                        onClick={() => handleRemove(item.product.id)}
                        aria-label="Remove item"
                      >
                        <i className="bi bi-trash"></i>
                      </button>
                    </div>
                    <p className="card-text">Subtotal: ${(item.product.price * item.quantity).toFixed(2)}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div className="d-flex justify-content-between align-items-center">
            <div>
              <strong>Total: </strong>
              ${cart.reduce((total, item) => total + item.product.price * item.quantity, 0).toFixed(2)}
            </div>
            <Link href="/checkout" className="btn btn-primary btn-lg">
              Proceed to Checkout
            </Link>
          </div>
        </>
      ) : (
        <div className="alert alert-info">Your cart is empty. <Link href="/products">Shop now</Link></div>
      )}
    </div>
  );
}
